version: '3'

services:
  mininet:
    build:
      context: .
    image: iwaseyusuke/mininet:ubuntu-22.04
    tty: true
    privileged: true
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /lib/modules:/lib/modules
      - ./:/scripts
  floodlight:
    build:
      context: .
    image: floodlight-imagev2
    ports:
      - "8080:8080"
      - "6653:6653"
      - "6633:6633"
